### ISSUE TITLE
Does this support SSML Tags?

### ISSUE THREAD

**Issue by Lensman-86** [StachePL/ExcelToAmazonPolly#4]
Does this program support both standard and Amazon Polly-specific SSML tags? If so, would a user simply add the tags into the "Line" field surrounding text as explained in amazon's guide?

Any and all help is appreciated.

**Comment by Lensman-86** [comment]
A few additional Questions:

1) does this program support multiple sheets in excel? 
     a) if so, how does that work?
2) are only the initial 5 columns read? (File, Line, Voice, Lexicons, Generate)? 
     - I use the 6th column to keep track of character count, and have been wondering if i can keep that, 
       or if i'll need to remove the column

**Comment by StachePL** [comment]
Yes it does support SSML tags. Remember to check the SSML field on the top bar.
1.a - Not at the moment
2 - I think you can use more columns, they shouldn't break anything as long as they have unique names.
